Traffic light classifier
Labonneguigue/CarND-Capstone-System-Integration pull request #10
Opened 2018-04-04 00:10 UTC by manu291

This detects and classifies the traffic lights on the camera image.
To test it use:
```bash
roslaunch launch/styx.launch log_level:=debug
```
Check "Camera" and uncheck "Manual". Look at the debug info in the terminal and check that it is consistent.

Note:
Initially I thought about simply fine tuning a classifier on the camera images. But it turned out it was not good enough, I still got around 10-15% of images wrongly classified. I believe this is because it is hard to classify images that vary a lot in size with just a classifier. So finally I use a detector taken from the tensorflow object detection API. It is maintained by the Tensorflow team and part of the standard Tensorflow tools.

2018-04-05 07:59 UTC, manu291 commented
Note: This is to be reviewed after PR #7 and PR #8 as it is based on the corresponding branches.

2018-04-14 19:33 UTC, Labonneguigue commented
@manu291 Could you please update this branch with the latest from master please ?
Could you please specify the expected behavior in the simulator ? 
Cheers

2018-04-14 21:19 UTC, Labonneguigue requested changes
Can't really test in the simulator. Massive latency.
I am trying to find a solution.
(2 comments)

2018-04-14 21:19 UTC, Labonneguigue commented on ros/src/tl_detector/tl_detector.py
> +        self.find_stop_line_closest_waypoints()
If there are several callbacks for the base_waypoints, the calculations for finding the traffic lights' stop lines are duplicated.

2018-04-14 21:19 UTC, Labonneguigue commented on ros/src/tl_detector/tl_detector.py
> +            distance = (wp_pos.x - pos.x) ** 2 + (wp_pos.y - pos.y) ** 2 + (wp_pos.z - pos.z) ** 2
I feel like it is not necessary to compute this at each frame. 
We could take the final_waypoints from the waypoint updater and based upon the first value (which will be the closest_waypoint) and its distance to the next traffic light location, we could trigger the traffic light detection or not. What do you think ?

2018-04-15 20:33 UTC, manu291 commented
@Labonneguigue Expected behavior: The debug log should output the correct state of the traffic light ahead whenever it is within 120 meters of the car and visible from the camera.

2018-04-16 19:17 UTC, Labonneguigue approved these changes

2018-04-16 19:21 UTC, merged